clans = {
    "#U8R80VUR",
    "#RQGGLV20",
    "#VC2Y0V9",
    "#RJLCJ9P",
    "#P0LYJC8C",
    "#8VQCC2YP",
    "#20YRUQRLJ",
    "#8RY0VRYL",
    "#9PL8Y89",
    "#9GQVL988",
    "#9VU8JG",
    "#2C0CL9UU",
    "#RRLYGYPG",
    "#290QQPRQU",
    "#9YVY9C8J",
    "#22LCQJLG2",
}

clan_names = {
    "Betatron",
    "Potato’s Diner",
    "Reddit Zero",
    "!One Love!",
    "Aussie Warriors",
    "Under 8s Team",
    "New Excalibur",
    "Gobinluil",
    "V.F RELOADED",
    "Canadian Kings",
    "Source of Logic",
    "Reddit Hotel",
    "squad",
    "!Mini Love!",
    "CrOsseyeCyclops",
    "Unfair Warfare",
}